### ISSUE TITLE
Create pages of available grants and ongoing projects

### ISSUE THREAD

**Issue by Brian2795** [Brian2795/828D#19]
- user should be able to toggle between the two pages
- both pages should take up the right side of the screen
- user should be able to scroll down an infinite list of projects of grants

**Comment by tongning** [comment]
Added. Keeping this open because it still needs to be scrollable.

**Comment by tongning** [comment]
Kinetic scrolling added via 116ee686246d8ee9dd79227b4e07dcbf8007c32f
